#!/bin/bash

if [ -d "node_modules" ]; then
    rm -r node_modules
    REMOVE_PACKAGE_LOCK=true
fi

if [ -f "package-lock.json" ] && [ "$REMOVE_PACKAGE_LOCK" = true ]; then
    rm package-lock.json
fi

npm install
# npm install --save-dev prettier prettier-plugin-apex lint-staged husky

SFDX_PLUGINS=$(cat ./config/dev-config.json | jq -r '.sfdxPlugins[]')

if [[ ! -z "${SFDX_PLUGINS// }" ]]; then
    PLUGIN_ALLOW_LIST=$(cat ./config/dev-config.json | jq -r '.sfdxPlugins')
    mkdir -p $HOME/.config/sfdx
    pushd .
    cd $HOME/.config/sfdx
    echo "$PLUGIN_ALLOW_LIST" > unsignedPluginAllowList.json
    popd
    sfdx plugins:install $SFDX_PLUGINS
fi

if [[ "$SFDX_PLUGINS" == *"sfdx-deliverability-access"* ]]; then
  cd ~/.local/share/sfdx/node_modules/puppeteer && npm install
fi

exit