#!/bin/bash
set -e
echo "Turning on all emails for Email Deliverability using args $@"

ORG_INFO="$(sfdx force:org:display $@ --verbose 2>/dev/null)"
INSTANCE_URL=$(echo "$ORG_INFO" | awk -F "Instance Url" '{print $2}' | xargs)
INSTANCE_LIGHTNING_URL=$(echo $INSTANCE_URL | sed -e 's/my\.sales/lightning\./g')
EMAIL_SETTINGS_URL="${BLUE_BOLD}${INSTANCE_LIGHTNING_URL}/lightning/setup/OrgEmailSettings/home${COLOR_RESET}"
plugins=$(sfdx plugins)
if [[ ! $plugins =~ "deliverability-access" ]];
then
    echo -e "${YELLOW}Use the following URL to turn on Email Deliverability access in UAT:${COLOR_RESET}\n${EMAIL_SETTINGS_URL}"
else
    echo -e "${YELLOW}Note:${COLOR_RESET} Attempting to turn on Email Deliverability access using sfdx-deliverability-access plugin..."
    sfdx deliverability:access -l all $@
    echo -e "\n${YELLOW}If sfdx-deliverability-access failed use the following URL to turn on Email Deliverability access in UAT:${COLOR_RESET}\n${EMAIL_SETTINGS_URL}"
fi